# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 084dffe916e5bf2bebba277ad61790999133f0764fd670052adbf3286af968428e9b502d7e32f62b67c57c93a2e71957bde11fdc30b9f3b69048e8f65146b6cf

test:
  secret_key_base: 3b654f89be53899cd8c5d29d31b34b7ba2660273d95367411e609e2dcee39102c5cce19d2dd17eb6df96c566f1e8c116ba22ae1b37347c0059e7958d2b915f17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
